# Config for a DGX-1 V100 reporting to production schema [PyTorch Tests]
test_environment: 'brain-lab'
# System basics
platform: 'NVIDIA'
platform_type: 'DGX-1 (V100)'

# Build type info
channel: FINAL
build_type: OTB
track: True

# reporting
report_auth: 'brain_lab_benchmarks.json'
report_project: 'google.com:tensorflow-performance'
report_dataset: 'benchmark_results'
report_table: 'result'

# pytorch tests to run.
pytorch_tests:
  - warmup_resnet_imagenet_128_gpu_8_real
  - renset50_128_gpu_1_real
  - renset50_128_gpu_2_real
  - renset50_128_gpu_4_real
  - renset50_128_gpu_8_real

input_threads: 36
