# Config for a GCE reporting to production schema.
test_environment: 'gce'
# System basics
# platform is not part of the key in the dashboard.
platform: 'gce'
platform_type: 'v100-Alpha'

# Build type info
channel: NIGHTLY
build_type: OTB

# reporting
report_auth: 'gce_upload.json'
report_project: 'google.com:tensorflow-performance'
report_dataset: 'benchmark_results'
report_table: 'result'

# tf-cnn-benchmarks
tf_cnn_bench_configs:
  - benchmark_harness/oss_bench/test_runners/tf_cnn_bench/configs/io_warmup_real.yaml
  - benchmark_harness/oss_bench/test_runners/tf_cnn_bench/configs/dgx_v100_real.yaml
  - benchmark_harness/oss_bench/test_runners/tf_cnn_bench/configs/dgx_v100.yaml
  - benchmark_harness/oss_bench/test_runners/tf_cnn_bench/configs/dgx_io_test_real.yaml

tf_models_tests:
  - 'resnet50_256_gpu_1_real_fp16'
  - 'resnet50_256_gpu_8_real_fp16'
