# Default config assumes usage of docker and local GPU at least GTX1080
test_harness: 'tf_cnn_benchmark'
test_environment: 'development-docker'
# System basics
platform: 'workstation'
platform_type: 'z420'

# reporting
report_auth: 'nightly_benchmark_dev.json'
# LOCAL causes results to be printed to the console not big table.
report_project: 'LOCAL'
report_dataset: 'benchmark_results_dev'
report_table: 'result'

# tf-cnn-benchmarks
#tf_cnn_bench_configs:
#  - benchmark_harness/oss_bench/test_runners/tf_cnn_bench/configs/workstation_gtx1080.yaml

tf_models_tests:
  - 'resnet50_32_gpu_1_real'
