# Test config for DGX-1
test_harness: 'tf_cnn_benchmark'
test_environment: 'development-docker'
# System basics
platform: 'NVIDIA'
platform_type: 'DGX-1 (P100)'

# reporting
report_auth: 'nightly_benchmark_dev.json'
report_project: 'google.com:tensorflow-performance'
report_dataset: 'benchmark_results_dev'
report_table: 'result'

# tf-cnn-benchmarks
tf_cnn_bench_configs:
  - benchmark_harness/oss_bench/test_runners/tf_cnn_bench/configs/dgx_p100_real.yaml
  - benchmark_harness/oss_bench/test_runners/tf_cnn_bench/configs/dgx_p100.yaml

# keras benchmarks
keras_tf_models_tests:
  - 'resnet50_64_gpu_1_synthetic'