# General settings
repeat: 5

# override sub_configs
num_batches: 100
nodistortions: FLAG_ONLY

# K80 Synthetic seemed to benefit form 2 vs. 1 thread.
# Additional analysis could be useful.
per_gpu_thread_count: 2

sub_configs:
  - '../tests/resnet/64/resnet50.1_gpu.64.ps_gpu.yaml'
  - '../tests/resnet/64/resnet50.2to4_gpu.64.yaml'
  - '../tests/resnet/64/resnet50.8_gpu.64.yaml'
  - '../tests/resnet/128/resnet50.1_gpu.128.ps_gpu.cuda_visible_0.yaml'
  - '../tests/resnet/128/resnet50.2to4_gpu.128.nccl.yaml'
  - '../tests/resnet/128/resnet50.8_gpu.128.replicated_nccl.prefetch.yaml'
