# General settings
repeat: 5

# Worker settings override
num_batches: 100
nodistortions: FLAG_ONLY

# Synthetic tests do not support prefetch and it does not matter.
datasets_use_prefetch: False

sub_configs:
  - '../tests/resnet/64/resnet50.1_gpu.64.ps_gpu.yaml'
  - '../tests/resnet/64/resnet50.2to4_gpu.64.yaml'
  - '../tests/resnet/64/resnet50.8_gpu.64.yaml'
