# General settings
repeat: 5

# override sub_configs
num_batches: 100
num_warmup_batches: 10
nodistortions: FLAG_ONLY
# Data directory mounted in the docker
data_dir: '/data/imagenet'
# Causes .real to be appended to all test_ids if data_dir is found.
test_id_hacks: True

sub_configs:
  - '../tests/resnet/64/resnet50.1_gpu.64.ps_gpu.yaml'
  - '../tests/resnet/64/resnet50.2to4_gpu.64.yaml'
  - '../tests/resnet/64/resnet50.8_gpu.64.yaml'
  - '../tests/resnet/128/resnet50.1_gpu.128.ps_gpu.cuda_visible_0.yaml'
  - '../tests/resnet/128/resnet50.2to4_gpu.128.nccl.yaml'
  - '../tests/resnet/128/resnet50.8_gpu.128.replicated_nccl.prefetch.yaml'
