# General settings
repeat: 5

# override sub_configs
num_batches: 100
nodistortions: FLAG_ONLY

sub_configs:
  - '../tests/resnet/128/resnet50.1_gpu.128.ps_gpu.cuda_visible_0.yaml'
  - '../tests/resnet/128/resnet50.2to4_gpu.128.nccl.yaml'
  - '../tests/resnet/128/resnet50.8_gpu.128.replicated_nccl.prefetch.yaml'
  - '../tests/resnetv1_5/128/resnet50v_1_5.1_gpu.128.ps_gpu.cuda_visible_0.yaml'
  - '../tests/resnetv1_5/128/resnet50v_1_5.2to4_gpu.128.nccl.yaml'
  - '../tests/resnetv1_5/128/resnet50v_1_5.8_gpu.128.replicated_nccl.prefetch.yaml'
