# General settings
repeat: 3

# Worker settings override
num_batches: 100
nodistortions: FLAG_ONLY

# Synthetic tests do not support prefetch and it does not matter.
datasets_use_prefetch: False

sub_configs:
  - 'tests/resnet/128/resnet50.1_gpu.128.ps_gpu.cuda_visible_0.yaml'
  - 'tests/resnet/128/resnet50.8_gpu.128.replicated_nccl.prefetch.yaml'
  - 'tests/resnet/128/resnet50.8_gpu.128.replicated_hierarchical_repacking.prefetch.yaml'
  - 'tests/resnet/64/resnet50.1_gpu.64.ps_gpu.nhwc.yaml'
  - 'tests/resnet/64/resnet50.1_gpu.64.ps_gpu.yaml'
  - 'tests/resnet/64/resnet50.8_gpu.64.replicated_hierarchical_repacking.yaml'
  - 'tests/vgg/vgg16.1_gpu.64.ps_gpu.yaml'
  - 'tests/vgg/vgg16.8_gpu.64.replicated_nccl.yaml'
  - 'tests/resnetv1_5/128/resnet50v_1_5.1_gpu.128.ps_gpu.cuda_visible_0.yaml'
  - 'tests/resnetv1_5/128/resnet50v_1_5.8_gpu.128.replicated_nccl.prefetch.yaml'
