# General settings
repeat: 3

# Worker settings override
num_batches: 100
nodistortions: FLAG_ONLY

sub_configs:
  - 'tests/resnetv1_5/256/resnet50v_1_5.1_gpu.256.ps_gpu.cuda_visible_0.xla.fp16.yaml'
  - 'tests/resnetv1_5/256/resnet50v_1_5.8_gpu.256.replicated_nccl.xla.full_twink.fp16.yaml'
  - 'tests/resnetv1_5/256/resnet50v_1_5.8_gpu.256.replicated_nccl.xla.fp16.yaml'
