# General settings
repeat: 3

# Worker settings override
num_batches: 100
num_warmup_batches: 100
nodistortions: FLAG_ONLY

# Data directory mounted in the docker
data_dir: '/data/imagenet'
# Causes .real to be appended to all test_ids if data_dir is found.
test_id_hacks: True

sub_configs:
  - 'tests/resnet/128/resnet50.1_gpu.forward_only.128.ps_gpu.cuda_visible_0.fp16.yaml'
  - 'tests/resnet/128/resnet50.1_gpu.128.ps_gpu.cuda_visible_0.fp16.yaml'
  - 'tests/resnet/256/resnet50.1_gpu.256.ps_gpu.cuda_visible_0.fp16.yaml'
  - 'tests/resnet/256/resnet50.8_gpu.256.replicated_hierarchical_repacking.prefetch.fp16.yaml'
  - 'tests/resnet/256/resnet50.8_gpu.256.replicated_nccl.prefetch.fp16.yaml'
  - 'tests/resnet/256/resnet50.2to4_gpu.256.replicated_hierarchical_repacking.prefetch.fp16.yaml'
  - 'tests/resnet/256/resnet50.2to4_gpu.256.replicated_nccl.fp16.yaml'
  - 'tests/resnet/256/resnet50.8_gpu.256.replicated_hierarchical_repacking.prefetch.nhwc.fp16.yaml'
  - 'tests/vgg/vgg16.1_gpu.128.ps_gpu.yaml'
  - 'tests/vgg/vgg16.8_gpu.128.replicated_nccl.yaml'
  - 'tests/resnetv1_5/256/resnet50v_1_5.8_gpu.256.replicated_nccl.prefetch.fp16.yaml'
  - 'tests/resnetv1_5/256/resnet50v_1_5.1_gpu.256.ps_gpu.cuda_visible_0.fp16.yaml'
  
