# General settings
repeat: 3

# Worker settings override
num_batches: 100
nodistortions: FLAG_ONLY

# Data directory mounted in the docker
data_dir: '/data/imagenet'
# Causes .real to be appended to all test_ids if data_dir is found.
test_id_hacks: True

sub_configs:
  - 'tests/resnet/64/resnet50.1_gpu.64.ps_gpu.yaml'

